/*Base de Datos proyecto Lenguajes de base de datos*/

/*Prueba Jeysus*/
/*Prueba Nicole*/

/*CREATE E INSERT DE LAS TABLAS*/
CREATE TABLE PROVINCIA
    (
            IDPROVINCIA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY NOT NULL, --"INCREMENTAL"
            NOMBRE VARCHAR2(20)
    );
    
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('San José'); 
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('Alajuela'); 
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('Cartago'); 
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('Heredia'); 
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('Guanacaste'); 
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('Puntarenas '); 
INSERT INTO PROVINCIA(NOMBRE)
          VALUES('Limón '); 
                    
SELECT * FROM PROVINCIA;

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

CREATE TABLE CANTON
    (
            IDCANTON NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY NOT NULL, --"INCREMENTAL"
            NOMBRE VARCHAR2(20),
            IDPROVINCIA NUMBER,
            foreign key(IDPROVINCIA) references PROVINCIA(IDPROVINCIA)
    );
    
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San José', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Acosta', 1);           
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Alajuelita', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Aserrí', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Curridabat', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Desamparados', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Dota', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Escazú', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Goicoechea', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('León Cortés', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Montes de Oca', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Mora', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Moravia', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Pérez Zeledón', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Puriscal', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Santa Ana', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Tarrazú', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Tibás', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Turrubares', 1); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Vázquez de Coronado', 1); 

INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Alajuela', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Atenas', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Grecia', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Guatuso', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Los Chiles', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Naranjo', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Orotina', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Palmares', 2);           
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Poás', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Río Cuarto', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San Carlos', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San Mateo', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San Ramón', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Sarchí', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Upala', 2); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Zarcero', 2); 

INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Cartago', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Alvarado', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('El Guarco', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Jiménez', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('La Unión', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Oreamuno', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Paraíso', 3); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Turrialba', 3); 

INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Heredia', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Barva', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Belén', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Flores', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San Isidro', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San Pablo', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('San Rafael', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Santa Bárbara', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Santo Domingo', 4); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Sarapiquí', 4); 

INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Liberia', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Abangares', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Bagaces', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Cañas', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Carrillo', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Hojancha', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('La Cruz', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Nandayure', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Nicoya', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Santa Cruz', 5); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Tilarán', 5); 

INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Puntarenas', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Esparza', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Buenos Aires', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Montes de Oro', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Osa', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Hojancha', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Quepos', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Coto Brus', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Parrita', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Corredores', 6); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Garabito', 6); 

INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Limón', 7); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Guácimo', 7); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Matina', 7); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Pococí', 7); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Siquirres', 7); 
INSERT INTO CANTON(NOMBRE, IDPROVINCIA)
          VALUES('Talamanca', 7); 

SELECT * FROM CANTON;

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

CREATE TABLE DISTRITO
    (
            IDDISTRITO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY NOT NULL, --"INCREMENTAL"
            NOMBRE VARCHAR2(20),
            IDCANTON NUMBER,
            foreign key(IDCANTON) references CANTON(IDCANTON)
    );

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Carmen', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Merced', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Hospital', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Catedral', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Zapote', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Francisco de Dos Ríos', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Uruca', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Mata Redonda', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Pavas', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Hatillo', 1); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Sebastián', 1); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Ignacio', 2); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Guaitil', 2); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Palmichal', 2); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Cangrejal', 2); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Sabanillas', 2);         
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Alajuelita', 3); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Josecito', 3); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Antonio', 3); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Concepción', 3); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Felipe', 3); 
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Aserrí', 4); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Legua', 4); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Monterrey', 4); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Tarbaca', 4); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Salitrillos', 4); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Gabriel', 4); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Vuelta de Jorco', 4); 
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Curridabat ', 5); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Granadilla', 5); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Tirrases ', 5); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Sánchez', 5);
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Desamparados ', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Miguel', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Juan de Dios ', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael Arriba', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Antonio', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Frailes', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Patarrá', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Cristóbal', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Rosario', 6);           
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Damas', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael Abajo', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Gravilias', 6); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Los Guido', 6);

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Santa María', 7); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('El Jardín', 7); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Copey', 7); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('El General', 7);
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Ureña', 7); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Rivas', 7); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Daniel Flores', 7); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Escazú', 8); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Antonio', 8); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael', 8); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Guadalupe', 9);
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Francisco', 9); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Calle Blancos', 9); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Mata de Plátano', 9); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Ipís', 9); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Rancho Redondo', 9); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Purral', 9); 
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Pablo', 10);
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Andrés', 10); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Llano Bonito', 10); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Isidro', 10); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Santa Cruz', 10); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Antonio', 10); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Pedro', 11); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Sabanilla', 11); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Mercedes', 11); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael', 11); 
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Colón', 12); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Guayabo', 12); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Tabarcia', 12); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Piedras Negras', 12); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Picagres', 12); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Jaris', 12); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Quitirrisí', 12);  
 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Vicente', 13); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Jerónimo', 13); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('La Trinidad', 13);  

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Isidro de El General', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('El General', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Daniel Flores', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Rivas', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Pedro', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Platanares', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Pejibaye', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Cajón', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Barú', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Río Nuevo', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Páramo', 14);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('La Amistad', 14);

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Santiago', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Mercedes Sur', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Barbacoas', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Grifo Alto', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Candelarita', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Desamparaditos', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Antonio', 15);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Chires', 15); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Santa Ana', 16);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Salitral', 16);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Pozos', 16); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Uruca', 16);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Piedades', 16);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Brasil', 16); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Marcos', 17);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Lorenzo', 17);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Carlos', 17); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Juan', 18);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Cinco Esquinas', 18);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Anselmo Llorente', 18);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('León XIII', 18);  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Colima', 18);    
          
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Pablo', 19); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Pedro', 19); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Juan de Mata', 19); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Luis', 19); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Carara', 19); 

INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Isidro', 20); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael', 20); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Dulce Nombre de Jesús', 20); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Patalillo', 20); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Cascajal', 20); 
  
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Alajuela', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San José', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Carrizal', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Antonio', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Guácima', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Isidro', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Sabanilla', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('San Rafael', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Río Segundo', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Desamparados', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Turrúcares', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Tambor', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Garita', 21); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('Sarapiquí', 21); 
 --insertado hasta aqui 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('', 22); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('', 22);
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('', 22); 
INSERT INTO DISTRITO(NOMBRE, IDCANTON)
          VALUES('', 22);

SELECT * FROM DISTRITO;
SELECT * FROM CANTON;

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

CREATE TABLE DIRECCION
      (
            IDDIRECCION NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY NOT NULL, 
            IDPROVINCIA NUMBER, 
            IDCANTON NUMBER, 
            IDDISTRITO NUMBER, 
            IDDESCRIPCION VARCHAR2(100),
            foreign key(IDPROVINCIA) references PROVINCIA(IDPROVINCIA),
            foreign key(IDCANTON) references CANTON(IDCANTON),
            foreign key(IDDISTRITO) references DISTRITO(IDDISTRITO)
      );
      
INSERT INTO DIRECCION(IDPROVINCIA, IDCANTON, IDDISTRITO, IDDESCRIPCION)
          VALUES(1, 1, 1, 'FRENTE HOGAR COMUNITARIO'); 

SELECT * FROM DIRECCION;

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

CREATE TABLE EMPLEADOS
    (
            IDEMPLEADO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY NOT NULL, --"INCREMENTAL"
            NOMBRE VARCHAR2(50),
            APELLIDO VARCHAR2(50),
            TELEFONO NUMBER,
            CEDULA NUMBER,
            EMAIL VARCHAR2(50),
            PUESTO VARCHAR2(50),
            SALARIO NUMBER,
            IDDIRECCION NUMBER,
            foreign key(IDDIRECCION) references DIRECCION(IDDIRECCION)
    );
INSERT INTO EMPLEADOS(NOMBRE, APELLIDO, TELEFONO, CEDULA, EMAIL, PUESTO, SALARIO, IDDIRECCION)
          VALUES('ALEJANDRO', 'LOPEZ', 89983223, 109870123, 'ALOPEZ@GMAIL.COM', 'DOCTOR', 150000, 1);

SELECT * FROM EMPLEADOS;

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

CREATE TABLE CLIENTE
    (
            IDCLIENTE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY NOT NULL,
            NOMBRE VARCHAR2(50),
            APELLIDO VARCHAR2(50),
            TELEFONO NUMBER,
            EMAIL VARCHAR2(50),
            IDDIRECCION NUMBER,
            foreign key(IDDIRECCION) references DIRECCION(IDDIRECCION)
    );
    
INSERT INTO CLIENTE(NOMBRE, APELLIDO, TELEFONO, EMAIL, IDDIRECCION)
          VALUES('ESTER', 'ARAUZ', 70128711, 'ESTERLOPEZ3@GMAIL.COM', 1);

SELECT * FROM CLIENTE;

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

/*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */



